Artificial Neural Network (ANN) Regression

Importing the libraries

In [2]:
pip install openpyxl

Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf

In [4]:
tf.__version__ 

'2.16.0-rc0'

Part 1 Data Preprocessing

Importing the Dataset

In [5]:
df=pd.read_excel("Folds5x2_pp.xlsx")
df.head()

AT      V       AP     RH      PE
0  14.96  41.76  1024.07  73.17  463.26
1  25.18  62.96  1020.04  59.08  444.37
2   5.11  39.40  1012.16  92.14  488.56
3  20.86  57.32  1010.24  76.64  446.48
4  10.82  37.50  1009.23  96.62  473.90

In [6]:
x=df.iloc[:,:-1].values
x

array([[  14.96,   41.76, 1024.07,   73.17],
       [  25.18,   62.96, 1020.04,   59.08],
       [   5.11,   39.4 , 1012.16,   92.14],
       ...,
       [  31.32,   74.33, 1012.92,   36.48],
       [  24.48,   69.45, 1013.86,   62.39],
       [  21.6 ,   62.52, 1017.23,   67.87]])

In [7]:
y=df.iloc[:,-1].values
y

array([463.26, 444.37, 488.56, ..., 429.57, 435.74, 453.28])

Splitting The Data set into Training and Testing Set

In [8]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

Part 2 Building the ANN

Initiating the ANN

In [9]:
ann=tf.keras.models.Sequential()

Adding the first Input layer and first Hidden layer

In [10]:
ann.add(tf.keras.layers.Dense(units=6,activation="relu"))

Adding the second Hidden layer

In [11]:
ann.add(tf.keras.layers.Dense(units=6,activation="relu"))

Adding the output layer

In [12]:
ann.add(tf.keras.layers.Dense(units=1))

Part 3 Training The ANN model

Compiling the ANN model

In [13]:
ann.compile(optimizer='adam',loss="mean_squared_error")

Training The ANN Model on the training Set

In [15]:
# ann.fit(x_train,y_train, batch_size=32,epchos=32)
ann.fit(x_train, y_train, batch_size = 32, epochs = 100)


Epoch 1/100


240/240 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 123625.3906
Epoch 2/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 411.6391
Epoch 3/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 382.3847
Epoch 4/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 355.5863
Epoch 5/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 304.4081
Epoch 6/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 240.9157
Epoch 7/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 164.1415
Epoch 8/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 112.0221
Epoch 9/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 79.1902
Epoch 10/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 61.6747
Epoch 11/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 54.9708
Epoch 12/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 47.9121
Epoch 13/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 43.0460
Epoch 14/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 42.0054
Epoch 15/100
240/240 ━━━━━━━━━

Predicting the results of the test set

In [18]:
y_pred=ann.predict(x_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))


45/60 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step 

60/60 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step
[[429.26 431.23]
 [460.16 460.01]
 [463.62 461.14]
 ...
 [470.81 473.26]
 [437.9  438.  ]
 [456.95 463.28]]
